name: On Conditons
on:
  workflow_dispatch:
  push:
    # branches:
      # - main
      # - alpha
      # - dev
    tags:
      - k8s-prod-*
      - k8s-alpha-*
      - k8s-dev-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Dump github context
        run: echo '${{ toJSON(github) }}'
