name: On Conditons

on:
  workflow_dispatch:
  push:
    # branches:
      # - main
      # - alpha
      # - dev
    tags:
      - k8s-prod-*
      - k8s-alpha-*
      - k8s-dev-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Dump github context
        run: echo '${{ toJSON(github) }}'

      - name: get img tag from tag and commit sha
        id: git_tag
        run: |
          git_tag=${{ github.ref_name }}
          git_sha_prefix=$(echo ${{ github.sha }} | cut -c 1-7)
          img_tag=${git_tag}-${git_sha_prefix}
